server:
  port: 8080

spring:
  datasource:
    username: root
    password: 542270191MSzyl
    url: jdbc:mysql://localhost:3306/useraccount?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/*.xml

